name: Build and Push Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set up Docker Buildx (optional, but recommended)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-student-boot-app .
          docker tag my-student-boot-app aravind526526/student_database:latest
          
      # Push Docker image
      - name: Push Docker image
        run: |
          docker push aravind526526/student_database:latest
